<div class="table-responsive">
<table class="table table-striped">
    <tr>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
    </tr>
    <tr>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
    </tr>
    <tr>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
    </tr>
    <tr>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
    </tr>
    <tr>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
        <td>Name</td>
    </tr>
</table>
</div>